### ISSUE TITLE
Support for sentry-cli 2.0.1

### ISSUE THREAD

**Issue by pskow** [getsentry/sentry-fastlane-plugin#120] opened 2022-04-12 23:02 UTC
Hello!
When can we expect support for sentry-cli 2.0.1?

**Comment by mokagio** [comment] 2022-04-13 00:14
This is a duplicated of #117. Also, there's a PR, currently not yet merged, #119, that addresses this issue.

**Comment by philipphofmann** [comment] 2022-04-13 08:14
Yes, this is a duplicate of https://github.com/getsentry/sentry-fastlane-plugin/issues/117.

**Closed by philipphofmann** 2022-04-13 08:14 UTC
Labels: Platform: Cocoa
